### ISSUE TITLE
fails to unpack file named a.b.c.zip

### ISSUE THREAD

**Issue by vivainio** [gernest/kemi#1]
The file type detection in listUnpackers() has the bug where it fails to work with .zip file with multiple dots in the name (e.g. mypackage.1.0.zip).

**Comment by gernest** [comment]
@vivainio thanks for reporting. I just noticed that kemi was treating something like this as an error. Can you please update the package and try again to see if it is resolved?

Update by running

```
go get -u github.com/gernest/kemi
```

**Comment by vivainio** [comment]
Tried updating, and now it works fine. Thanks for the fast reponse :). You can close this ticket now

**Comment by gernest** [comment]
You are welcome
