### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by nagayev** [gernest/kemi#2]
Is this project abonded?
You can archive the repository if this is true.

**Comment by gernest** [comment]
This is very much alive, please open  an issue if you have one.

And any contributions are welcome.

**Comment by nagayev** [comment]
@gernest t's really cool.
I want to add support determition of file type
E.g if you see file.tar.gz you can guess it's arhive .tar.gz, but we can check first magic bytes.
I'm currently working on it.
